// Static taxonomy data parsed from MD files:
//   sektor_markdown_3sutun.md  → SEKTÖR + MESLEK tables
//   yetkinlikler (1).md        → YETKİNLİKLER table

export interface StaticSector { id: string; name: string }
export interface StaticOccupation { id: string; name: string }
export interface StaticUnit { id: string; name: string }
export interface StaticCompetency { id: string; name: string; category: string }

// ─── SEKTÖRLER ────────────────────────────────────────────────────────────────

export const STATIC_SECTORS: StaticSector[] = [
  { id: 's01', name: 'Ağaç ve ağaç ürünleri imalatı (mobilya hariç)' },
  { id: 's02', name: 'Ana metal sanayii' },
  { id: 's03', name: 'Atık toplama / işleme / bertaraf; geri kazanım' },
  { id: 's04', name: 'Başka yerde sınıflandırılmamış makine ve ekipman imalatı' },
  { id: 's05', name: 'Bilgi hizmet faaliyetleri' },
  { id: 's06', name: 'Bilgi ve iletişim' },
  { id: 's07', name: 'Bilgisayar programlama, danışmanlık ve ilgili faaliyetler' },
  { id: 's08', name: 'Bilgisayarların, elektronik ve optik ürünlerin imalatı' },
  { id: 's09', name: 'Bilgisayarların, kişisel ve ev eşyalarının onarımı' },
  { id: 's10', name: 'Bilimsel Ar-Ge' },
  { id: 's11', name: 'Bina dışı yapıların inşaatı (mühendislik yapıları)' },
  { id: 's12', name: 'Bina inşaatı' },
  { id: 's13', name: 'Bitkisel ve hayvansal üretim; avcılık ve ilgili hizmetler' },
  { id: 's14', name: 'Depolama ve taşımacılık için destekleyici faaliyetler' },
  { id: 's15', name: 'Deri ve ilgili ürünlerin imalatı' },
  { id: 's16', name: 'Diğer hizmet faaliyetleri' },
  { id: 's17', name: 'Diğer mesleki / bilimsel / teknik faaliyetler' },
  { id: 's18', name: 'Diğer metalik olmayan mineral ürünlerin imalatı' },
  { id: 's19', name: 'Diğer ulaşım araçlarının imalatı (gemi / tekne inşası)' },
  { id: 's20', name: 'Eğitim' },
  { id: 's21', name: 'Elektrik, gaz, buhar ve iklimlendirme üretimi ve dağıtımı' },
  { id: 's22', name: 'Elektrikli teçhizat imalatı' },
  { id: 's23', name: 'Fabrikasyon metal ürünleri imalatı (makine / teçhizat hariç)' },
  { id: 's24', name: 'Finansal hizmet faaliyetleri (sigorta / emeklilik hariç)' },
  { id: 's25', name: 'Finansal hizmetler ve sigorta için yardımcı faaliyetler' },
  { id: 's26', name: 'Gayrimenkul faaliyetleri' },
  { id: 's27', name: 'Gıda ürünlerinin imalatı' },
  { id: 's28', name: 'Giyim eşyalarının imalatı' },
  { id: 's29', name: 'Güvenlik ve soruşturma faaliyetleri' },
  { id: 's30', name: 'Hava yolu taşımacılığı' },
  { id: 's31', name: 'Hukuk ve muhasebe' },
  { id: 's32', name: 'İçeceklerin imalatı' },
  { id: 's33', name: 'İdare merkezi; idari danışmanlık' },
  { id: 's34', name: 'İmalat' },
  { id: 's35', name: 'İnsan sağlığı ve sosyal hizmetler' },
  { id: 's36', name: 'İnşaat' },
  { id: 's37', name: 'İstihdam faaliyetleri' },
  { id: 's38', name: 'Kağıt ve kağıt ürünlerinin imalatı' },
  { id: 's39', name: 'Kamu yönetimi ve savunma; zorunlu sosyal güvenlik' },
  { id: 's40', name: 'Kara taşımacılığı ve boru hattı taşımacılığı' },
  { id: 's41', name: 'Kauçuk ve plastik ürünlerin imalatı' },
  { id: 's42', name: 'Kimyasalların ve kimyasal ürünlerin imalatı' },
  { id: 's43', name: 'Kiralama ve leasing' },
  { id: 's44', name: 'Konaklama ve yiyecek hizmeti faaliyetleri' },
  { id: 's45', name: 'Kültür, sanat, eğlence, dinlence ve spor' },
  { id: 's46', name: 'Madencilik ve taş ocakçılığı' },
  { id: 's47', name: 'Mesleki, bilimsel ve teknik faaliyetler' },
  { id: 's48', name: 'Metal cevherleri madenciliği' },
  { id: 's49', name: 'Mimarlık ve mühendislik; teknik test ve analiz' },
  { id: 's50', name: 'Mobilya imalatı' },
  { id: 's51', name: 'Motorlu kara taşıtı, treyler ve yarı treyler imalatı' },
  { id: 's52', name: 'Motorlu taşıtların ve motosikletlerin ticareti ve onarımı' },
  { id: 's53', name: 'Özel inşaat faaliyetleri' },
  { id: 's54', name: 'Perakende ticaret (motorlu taşıtlar hariç)' },
  { id: 's55', name: 'Programcılık ve yayıncılık faaliyetleri' },
  { id: 's56', name: 'Reklamcılık ve piyasa araştırması' },
  { id: 's57', name: 'Seyahat acentesi / tur operatörü / rezervasyon' },
  { id: 's58', name: 'Sigorta, reasürans ve emeklilik fonları' },
  { id: 's59', name: 'Spor, eğlence ve dinlence' },
  { id: 's60', name: 'Su temini; kanalizasyon, atık yönetimi ve iyileştirme' },
  { id: 's61', name: 'Su yolu taşımacılığı' },
  { id: 's62', name: 'Tarım, ormancılık ve balıkçılık' },
  { id: 's63', name: 'Tekstil ürünlerinin imalatı' },
  { id: 's64', name: 'Telekomünikasyon' },
  { id: 's65', name: 'Temel eczacılık ürünleri ve ilgili malzemelerin imalatı' },
  { id: 's66', name: 'Toptan ticaret (motorlu taşıtlar hariç)' },
  { id: 's67', name: 'Tütün ürünleri imalatı' },
  { id: 's68', name: 'Ulaştırma ve depolama' },
  { id: 's69', name: 'Veterinerlik' },
  { id: 's70', name: 'Yaratıcı sanatlar, gösteri sanatları ve eğlence' },
  { id: 's71', name: 'Yayımcılık faaliyetleri' },
  { id: 's72', name: 'Yatılı bakım faaliyetleri' },
  { id: 's73', name: 'Büro yönetimi / destek ve iş destek faaliyetleri' },
  { id: 's74', name: 'Balıkçılık ve su ürünleri yetiştiriciliği' },
  { id: 's75', name: 'Ormancılık ve tomrukçuluk' },
];

// ─── MESLEKLER ────────────────────────────────────────────────────────────────
// NOTE: MD file does not provide sector-occupation mapping; all occupations
// are shown regardless of selected sector. sectorId kept for future mapping.

export const STATIC_OCCUPATIONS: StaticOccupation[] = [
  { id: 'o001', name: 'Ajans, organizasyon faaliyetleri' },
  { id: 'o002', name: 'Akaryakıt ticareti' },
  { id: 'o003', name: 'Aktar ürünleri imalatı, ticareti' },
  { id: 'o004', name: 'Alternatif tedavi merkezi işletmeciliği' },
  { id: 'o005', name: 'Alüminyum ürün imalatı' },
  { id: 'o006', name: 'Arıcılık' },
  { id: 'o007', name: 'Arzuhalcilik, danışmanlık, bilgi hizmetleri' },
  { id: 'o008', name: 'Asansör, yürüyen merdiven kurulumu, bakımı, onarımı' },
  { id: 'o009', name: 'Ayakkabıcılık' },
  { id: 'o010', name: 'Bakırcılık' },
  { id: 'o011', name: 'Bakkallık, bayilik, büfecilik' },
  { id: 'o012', name: 'Balıkçılık' },
  { id: 'o013', name: 'Basın, yayım, iletişim' },
  { id: 'o014', name: 'Besicilik, celeplik' },
  { id: 'o015', name: 'Beyaz eşya onarımı' },
  { id: 'o016', name: 'Beyaz eşya ticareti' },
  { id: 'o017', name: 'Bilgisayar kurulumu, onarımı, programlama, veri kurtarma' },
  { id: 'o018', name: 'Bireysel sanatkârlık faaliyetleri' },
  { id: 'o019', name: 'Bitkisel ürünlerle ilgili faaliyetler' },
  { id: 'o020', name: 'Boya, kimyasal ürünlerin imalatı' },
  { id: 'o021', name: 'Boya, kimyasal ürünlerin ticareti' },
  { id: 'o022', name: 'Börekçilik' },
  { id: 'o023', name: 'Camcılık' },
  { id: 'o024', name: 'Cenaze hizmetleri' },
  { id: 'o025', name: 'Çamaşırhane, kuru temizleme, ütücülük hizmetleri' },
  { id: 'o026', name: 'Çeşitli gıdaların imalatı' },
  { id: 'o027', name: 'Çeşitli malların ticareti' },
  { id: 'o028', name: 'Çevre düzenleme, peyzaj faaliyetleri' },
  { id: 'o029', name: 'Çiçekçilik' },
  { id: 'o030', name: 'Çilingirlik' },
  { id: 'o031', name: 'Değirmencilik, zahirecilik' },
  { id: 'o032', name: 'Demir, çelik eşya imalatı, ticareti' },
  { id: 'o033', name: 'Deniz taşıtları imalatı, onarımı, ticareti' },
  { id: 'o034', name: 'Deri aksesuar imalatı, ticareti' },
  { id: 'o035', name: 'Deri giyim eşyası imalatı, onarımı' },
  { id: 'o036', name: 'Deri giyim eşyası ticareti' },
  { id: 'o037', name: 'Dericilik' },
  { id: 'o038', name: 'Diş laboratuvarlarının faaliyetleri' },
  { id: 'o039', name: 'Dokumacılık' },
  { id: 'o040', name: 'Dondurmacılık' },
  { id: 'o041', name: 'Dökümcülük' },
  { id: 'o042', name: 'Dövme salonu işletmeciliği' },
  { id: 'o043', name: 'Durak, otopark işletmeciliği' },
  { id: 'o044', name: 'Düğün salonu işletmeciliği' },
  { id: 'o045', name: 'Eğlence yerleri işletmeciliği' },
  { id: 'o046', name: 'Elektrik makineleri imalatı, kurulumu, onarımı' },
  { id: 'o047', name: 'Elektrik malzemeleri imalatı, ticareti' },
  { id: 'o048', name: 'Elektrik sistemleri imalatı, kurulumu, onarımı' },
  { id: 'o049', name: 'Elektrik tesisatçılığı' },
  { id: 'o050', name: 'Elektrikli ev aletleri imalatı, onarımı' },
  { id: 'o051', name: 'Elektrikli ev aletleri ticareti' },
  { id: 'o052', name: 'Elektronik ürün imalatı, onarımı' },
  { id: 'o053', name: 'Elektronik ürün ticareti' },
  { id: 'o054', name: 'Emlakçılık' },
  { id: 'o055', name: 'Erkek berberliği' },
  { id: 'o056', name: 'E-ticaret' },
  { id: 'o057', name: 'Ev tekstil ürünleri imalatı, ticareti' },
  { id: 'o058', name: 'Evcil hayvan bakımı, ticareti' },
  { id: 'o059', name: 'Fırıncılık' },
  { id: 'o060', name: 'Fotoğrafçılık' },
  { id: 'o061', name: 'Gazinoculuk' },
  { id: 'o062', name: 'Genel temizlik, haşere kontrol faaliyetleri' },
  { id: 'o063', name: 'Gübre, zirai ilaç imalatı, ticareti' },
  { id: 'o064', name: 'Güvenlik sistemleri hizmetleri' },
  { id: 'o065', name: 'Güzellik salonu işletmeciliği' },
  { id: 'o066', name: 'Halı yıkama hizmetleri' },
  { id: 'o067', name: 'Halıcılık, kilimcilik' },
  { id: 'o068', name: 'Hasta bakıcılığı' },
  { id: 'o069', name: 'Hediyelik eşya imalatı, ticareti' },
  { id: 'o070', name: 'Hırdavatçılık' },
  { id: 'o071', name: 'Hurdacılık' },
  { id: 'o072', name: 'İkinci el eşya ticareti' },
  { id: 'o073', name: 'İklimlendirme, soğutma sistemi imalatı, kurulumu, onarımı' },
  { id: 'o074', name: 'İnşaat malzemeleri imalatı' },
  { id: 'o075', name: 'İnşaat malzemeleri ticareti' },
  { id: 'o076', name: 'İnşaatçılık' },
  { id: 'o077', name: 'İş makinesi işletmeciliği' },
  { id: 'o078', name: 'Kadın kuaförlüğü' },
  { id: 'o079', name: 'Kağıt, kağıt ürünleri imalatı, ticareti' },
  { id: 'o080', name: 'Kahvehanecilik, kıraathanecilik' },
  { id: 'o081', name: 'Kalaycılık, kaplamacılık' },
  { id: 'o082', name: 'Kantincilik' },
  { id: 'o083', name: 'Kaplıca, hamam işletmeciliği' },
  { id: 'o084', name: 'Kara yolu ile yük taşımacılığı' },
  { id: 'o085', name: 'Karoser imalatı, kaportacılık' },
  { id: 'o086', name: 'Kasaplık' },
  { id: 'o087', name: 'Kauçuk, plastik ürünlerin imalatı, ticareti' },
  { id: 'o088', name: 'Kerestecilik' },
  { id: 'o089', name: 'Kırtasiye imalatı, ticareti' },
  { id: 'o090', name: 'Kitapçılık' },
  { id: 'o091', name: 'Konfeksiyonculuk' },
  { id: 'o092', name: 'Kozmetik imalatı, ticareti' },
  { id: 'o093', name: 'Kreş işletmeciliği' },
  { id: 'o094', name: 'Kurs işletmeciliği' },
  { id: 'o095', name: 'Kuruyemiş imalatı, ticareti' },
  { id: 'o096', name: 'Kuyumculuk' },
  { id: 'o097', name: 'Lokantacılık' },
  { id: 'o098', name: 'Makine kurulumu, onarımı' },
  { id: 'o099', name: 'Makine, yedek parça ticareti' },
  { id: 'o100', name: 'Manavlık' },
  { id: 'o101', name: 'Marangozluk' },
  { id: 'o102', name: 'Matbaacılık' },
  { id: 'o103', name: 'Mermer, taş, kum ocakçılığı' },
  { id: 'o104', name: 'Meşrubat imalatı, ticareti' },
  { id: 'o105', name: 'Mobilya imalatı' },
  { id: 'o106', name: 'Mobilya ticareti' },
  { id: 'o107', name: 'Motosiklet, bisiklet imalatı, onarımı' },
  { id: 'o108', name: 'Motosiklet, bisiklet ticareti' },
  { id: 'o109', name: 'Müzik aletleri imalatı, onarımı, ticareti' },
  { id: 'o110', name: 'Nakliyat komisyonculuğu' },
  { id: 'o111', name: 'Optik ürünlerin imalatı, ticareti' },
  { id: 'o112', name: 'Otel, pansiyon, yurt işletmeciliği' },
  { id: 'o113', name: 'Oto bakım servisçiliği' },
  { id: 'o114', name: 'Oto boyacılık' },
  { id: 'o115', name: 'Oto elektrikçilik' },
  { id: 'o116', name: 'Oto galericilik, oto kiralama' },
  { id: 'o117', name: 'Oto lastik onarımı' },
  { id: 'o118', name: 'Oto yedek parça ticareti' },
  { id: 'o119', name: 'Oto yıkama, yağlama' },
  { id: 'o120', name: 'Otobüsçülük' },
  { id: 'o121', name: 'Oyun salonu, internet kafe işletmeciliği' },
  { id: 'o122', name: 'Oyuncak imalatı, ticareti' },
  { id: 'o123', name: 'Pastanecilik, tatlıcılık' },
  { id: 'o124', name: 'Pazarda sebze, meyve ticareti' },
  { id: 'o125', name: 'Pazarda yiyecek, içecek ticareti' },
  { id: 'o126', name: 'PVC ürün imalatı' },
  { id: 'o127', name: 'Reklamcılık, tabelacılık' },
  { id: 'o128', name: 'Saatçilik' },
  { id: 'o129', name: 'Sanat eseri, antika ticareti' },
  { id: 'o130', name: 'Ses, sahne sanatçılığı' },
  { id: 'o131', name: 'Seyyar satıcılık' },
  { id: 'o132', name: 'Sıhhi tesisatçılık' },
  { id: 'o133', name: 'Spor malzemeleri imalatı, ticareti' },
  { id: 'o134', name: 'Spor tesisi işletmeciliği' },
  { id: 'o135', name: 'Su yolu taşımacılığı' },
  { id: 'o136', name: 'Şarküteri ürünleri imalatı, ticareti' },
  { id: 'o137', name: 'Şekercilik, çikolatacılık' },
  { id: 'o138', name: 'Taksicilik' },
  { id: 'o139', name: 'Tasarım faaliyetleri' },
  { id: 'o140', name: 'Tavukçuluk' },
  { id: 'o141', name: 'Tekstil baskıcılığı, boyacılığı' },
  { id: 'o142', name: 'Telekomünikasyon cihazları onarımı' },
  { id: 'o143', name: 'Telekomünikasyon cihazları ticareti' },
  { id: 'o144', name: 'Temizlik malzemeleri imalatı, ticareti' },
  { id: 'o145', name: 'Tenekecilik' },
  { id: 'o146', name: 'Tercümanlık' },
  { id: 'o147', name: 'Terzilik' },
  { id: 'o148', name: 'Tıbbi malzemelerin imalatı, ticareti' },
  { id: 'o149', name: 'Tornacılık' },
  { id: 'o150', name: 'Tuhafiye imalatı, ticareti' },
  { id: 'o151', name: 'Tüp gaz bayiliği' },
  { id: 'o152', name: 'Yakacak imalatı, ticareti' },
  { id: 'o153', name: 'Yaş sebze, meyve ticareti' },
  { id: 'o154', name: 'Yük taşımacılığını destekleyici faaliyetler' },
  { id: 'o155', name: 'Züccaciye imalatı, ticareti' },
];

// ─── BİRİMLER (predefined common organizational units) ────────────────────────

export const STATIC_UNITS: StaticUnit[] = [
  { id: 'u01', name: 'Yönetim Birimi' },
  { id: 'u02', name: 'İnsan Kaynakları Birimi' },
  { id: 'u03', name: 'Satış ve Pazarlama Birimi' },
  { id: 'u04', name: 'Operasyon Birimi' },
  { id: 'u05', name: 'Finans ve Muhasebe Birimi' },
  { id: 'u06', name: 'Bilgi Teknolojileri Birimi' },
  { id: 'u07', name: 'Üretim Birimi' },
  { id: 'u08', name: 'Ar-Ge ve İnovasyon Birimi' },
  { id: 'u09', name: 'Müşteri Hizmetleri Birimi' },
  { id: 'u10', name: 'Kalite ve Süreç Yönetimi Birimi' },
  { id: 'u11', name: 'Tedarik Zinciri ve Lojistik Birimi' },
  { id: 'u12', name: 'Hukuk ve Uyum Birimi' },
];

// ─── YETKİNLİKLER (from yetkinlikler (1).md) ─────────────────────────────────

export const STATIC_COMPETENCIES: StaticCompetency[] = [
  // Bilişsel Yetkinlikler
  { id: 'c01', name: 'Analitik Düşünme',               category: 'Bilişsel Yetkinlikler' },
  { id: 'c02', name: 'Sayısal Akıl / Nicel Düşünme',   category: 'Bilişsel Yetkinlikler' },
  { id: 'c03', name: 'Sözel Akıl / Dilsel Anlama',     category: 'Bilişsel Yetkinlikler' },
  { id: 'c04', name: 'Eleştirel Düşünme',              category: 'Bilişsel Yetkinlikler' },
  { id: 'c05', name: 'Problem Çözme',                  category: 'Bilişsel Yetkinlikler' },
  { id: 'c06', name: 'Öğrenme Çevikliği',              category: 'Bilişsel Yetkinlikler' },
  { id: 'c07', name: 'Karar Verme',                    category: 'Bilişsel Yetkinlikler' },
  { id: 'c08', name: 'Bütünsel / Sistemsel Düşünme',   category: 'Bilişsel Yetkinlikler' },
  { id: 'c09', name: 'Yenilikçi / Yaratıcı Düşünme',  category: 'Bilişsel Yetkinlikler' },
  { id: 'c10', name: 'Dikkat ve Odaklanma',            category: 'Bilişsel Yetkinlikler' },

  // Teknik Yetkinlikler
  { id: 'c11', name: 'Teknik Problem Çözme (Arıza Giderme)',          category: 'Teknik Yetkinlikler' },
  { id: 'c12', name: 'Teknik Analitik Düşünme (Mühendislik Analizi)', category: 'Teknik Yetkinlikler' },
  { id: 'c13', name: 'Veri ile Çalışma (Data Literacy)',              category: 'Teknik Yetkinlikler' },
  { id: 'c14', name: 'Süreç Odaklılık',                               category: 'Teknik Yetkinlikler' },
  { id: 'c15', name: 'Planlama ve Organizasyon',                      category: 'Teknik Yetkinlikler' },
  { id: 'c16', name: 'Kalite ve Detay Duyarlılığı',                   category: 'Teknik Yetkinlikler' },
  { id: 'c17', name: 'Dijital Yetkinlik',                             category: 'Teknik Yetkinlikler' },
  { id: 'c18', name: 'Sürekli İyileştirme (Kaizen)',                  category: 'Teknik Yetkinlikler' },
  { id: 'c19', name: 'Sonuç ve Performans Takibi',                    category: 'Teknik Yetkinlikler' },
  { id: 'c20', name: 'Risk ve Önleyici Düşünme',                      category: 'Teknik Yetkinlikler' },

  // Temel Yetkinlikler
  { id: 'c21', name: 'İletişim',                                  category: 'Temel Yetkinlikler' },
  { id: 'c22', name: 'Takım Çalışması',                           category: 'Temel Yetkinlikler' },
  { id: 'c23', name: 'Sonuç Odaklılık',                           category: 'Temel Yetkinlikler' },
  { id: 'c24', name: 'Uyum Sağlama (Adaptasyon)',                 category: 'Temel Yetkinlikler' },
  { id: 'c25', name: 'Müşteri / Paydaş Odaklılık',               category: 'Temel Yetkinlikler' },
  { id: 'c26', name: 'Etik ve Güvenilirlik',                      category: 'Temel Yetkinlikler' },
  { id: 'c27', name: 'Öğrenme ve Gelişim',                        category: 'Temel Yetkinlikler' },
  { id: 'c28', name: 'İnisiyatif Alma',                           category: 'Temel Yetkinlikler' },
  { id: 'c29', name: 'İş Disiplini ve Sorumluluk',                category: 'Temel Yetkinlikler' },
  { id: 'c30', name: 'Öz Yönetim ve Önceliklendirme',             category: 'Temel Yetkinlikler' },

  // Yönetsel Yetkinlikler
  { id: 'c31', name: 'Stratejik Düşünme',                         category: 'Yönetsel Yetkinlikler' },
  { id: 'c32', name: 'Vizyoner Liderlik',                         category: 'Yönetsel Yetkinlikler' },
  { id: 'c33', name: 'Karar Verme ve Sorumluluk Alma',            category: 'Yönetsel Yetkinlikler' },
  { id: 'c34', name: 'Delegasyon ve Yetki Devri',                 category: 'Yönetsel Yetkinlikler' },
  { id: 'c35', name: 'Koçluk ve Ekip Geliştirme',                 category: 'Yönetsel Yetkinlikler' },
  { id: 'c36', name: 'Değişim Yönetimi',                         category: 'Yönetsel Yetkinlikler' },
  { id: 'c37', name: 'Finansal ve İş Odaklılık',                  category: 'Yönetsel Yetkinlikler' },
  { id: 'c38', name: 'İlişki ve Paydaş Yönetimi',                 category: 'Yönetsel Yetkinlikler' },
  { id: 'c39', name: 'İnovasyon ve Sürekli İyileştirme',          category: 'Yönetsel Yetkinlikler' },
  { id: 'c40', name: 'Kriz ve Risk Yönetimi',                     category: 'Yönetsel Yetkinlikler' },
];
